### ISSUE TITLE
Cocotb version referenced as a submodule is not publicly available...

### ISSUE THREAD

**Issue by rbarzic** [mciepluc/apbi2c_cocotb_example#1]
Shell commands:

git clone https://github.com/mciepluc/apbi2c_cocotb_example.git
cd apbi2c_cocotb_example
git submodule update --init 

Result:
Submodule 'apbi2c' (https://github.com/freecores/apbi2c) registered for path 'apbi2c'
Submodule 'cocotb' (https://github.com/mciepluc/cocotb) registered for path 'cocotb'
Cloning into '/home/roba/perso/github/apbi2c_cocotb_example/apbi2c'...
Cloning into '/home/roba/perso/github/apbi2c_cocotb_example/cocotb'...
Submodule path 'apbi2c': checked out '1f18d2b70703fbc436a50e917edf679d9337461c'
error: Server does not allow request for unadvertised object 7fed0c25723648630bb97808c37892bb5018c366
Fetched in submodule path 'cocotb', but it did not contain 7fed0c25723648630bb97808c37892bb5018c366. Direct fetching of that commit failed.

Probably a local version of cocotb  not pushed to github ?

**Comment by rbarzic** [comment]
Probably the cocotb version that includes constraint random verification and coverage  extension....

**Comment by mciepluc** [comment]
Hi @rbarzic, 
You are right, there was previously cocotb version with built-in extensions, but know it will use default Cocotb distribution and [cocotb-coverage](https://github.com/mciepluc/cocotb-coverage) package. I will update this soon.

**Comment by mciepluc** [comment]
Updated externals in the repo and everything works now.
